//HintName: ColorTestForClassWithString.g.cs
/// <auto-generated />

[System.Serializable]
public class ColorTestForClassWithString
{
    [UnityEngine.SerializeField] private ClassWithString Red;
    [UnityEngine.SerializeField] private ClassWithString Blue;
    [UnityEngine.SerializeField] private ClassWithString Green;

    public ColorTestForClassWithString() { }

    public ColorTestForClassWithString(ClassWithString red, ClassWithString blue, ClassWithString green)
    {
        this.Red = red;
        this.Blue = blue;
        this.Green = green;
    }

    public ClassWithString Get(ColorTest key)
    {
        return key switch
        {
            ColorTest.Red => Red,
            ColorTest.Blue => Blue,
            ColorTest.Green => Green,
            _ => throw new System.ArgumentOutOfRangeException(nameof(key), key, null),
        };
    }

    public void Set(ColorTest key, ClassWithString value)
    {
        switch (key)
        {
            case ColorTest.Red: Red = value; break;
            case ColorTest.Blue: Blue = value; break;
            case ColorTest.Green: Green = value; break;
            default: throw new System.ArgumentOutOfRangeException(nameof(key), key, null);
        }
    }

    public void Apply(ColorTest key, System.Func<ClassWithString, ClassWithString> func)
    {
        switch (key)
        {
            case ColorTest.Red: Red = func(Red); break;
            case ColorTest.Blue: Blue = func(Blue); break;
            case ColorTest.Green: Green = func(Green); break;
            default: throw new System.ArgumentOutOfRangeException(nameof(key), key, null);
        }
    }
}
