using UnityAttributes.Common;

namespace UnityAttributes.PublicAccessor;

public partial class PublicAccessorGenerator {
  public const string AttributeName = "PublicAccessorAttribute";
  readonly string attributeText = @$"{Const.AutoGeneratedText}

{generatedCodeAttribute}
[global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = true, AllowMultiple = false)]
internal sealed class {AttributeName} : global::System.Attribute {{
  public {AttributeName}() {{ }}
}}
";
}