namespace UnityAttributes.PublicAccessor;

public partial class PublicAccessorGenerator {
  public const string AttributeName = "PublicAccessorAttribute";
  readonly string attributeText = @$"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

{generatedCodeAttribute}
[global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = true, AllowMultiple = false)]
internal class PublicAccessorAttribute : global::System.Attribute {{
  public PublicAccessorAttribute() {{ }}
}}
";
}