//HintName: PublicAccessorAttribute.g.cs
/// <auto-generated />

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("UnityAttributes", "1.4.0.0")]
[global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = true, AllowMultiple = false)]
internal sealed class PublicAccessorAttribute : global::System.Attribute
{
    internal PublicAccessorAttribute()
    {
    }
}
