//HintName: Test2.TestClass.NestedClass.g.cs
/// <auto-generated />

namespace Test2
{
    public partial class TestClass
    {
        public partial class NestedClass
        {
            /// Public accessor for <see cref="_value"/>
            /// <inheritdoc cref="_value"/>
            public int Value => _value;
        }
    }
}
