//HintName: Test1.TestClass.g.cs
/// <auto-generated />

namespace Test1
{
    public partial class TestClass
    {
        /// Public accessor for <see cref="_value1"/>
        /// <inheritdoc cref="_value1"/>
        public int Value1 => _value1;

        /// Public accessor for <see cref="value2"/>
        /// <inheritdoc cref="value2"/>
        public int Value2 => value2;

        /// Public accessor for <see cref="Value3"/>
        /// <inheritdoc cref="Value3"/>
        public int _Value3 => Value3;
    }
}
