//HintName: Test2.TestClass.g.cs
/// <auto-generated />

namespace Test2
{
    public partial class TestClass
    {
        /// Public accessor for <see cref="_nestedClass"/>
        /// <inheritdoc cref="_nestedClass"/>
        public Test2.TestClass.NestedClass NestedClass => _nestedClass;
    }
}
