//HintName: GenConstructorAttribute.g.cs
/// <auto-generated />

[global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = true, AllowMultiple = false)]
internal sealed class GenConstructorAttribute : global::System.Attribute
{
    internal GenConstructorAttribute()
    {
    }
}
