//HintName: GenConstructorIgnoreAttribute.g.cs
/// <auto-generated />

[global::System.AttributeUsage(global::System.AttributeTargets.Field, Inherited = true, AllowMultiple = false)]
internal sealed class GenConstructorIgnoreAttribute : global::System.Attribute
{
    internal GenConstructorIgnoreAttribute()
    {
    }
}
