//HintName: Test1.TestClass.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1
{
    public partial class TestClass
    {
        public TestClass(int value1, int value2, int value3, int value6)
        {
            this._value1 = value1;
            this._value2 = value2;
            this.value3 = value3;
            this.Value6 = value6;
        }
    }
}
