namespace UnityAttributes.EnumTypeFor;

public static class EnumTypeForAttribute
{
    public const string ATTRIBUTE_SHORT_NAME = "EnumTypeFor";
    public const string ATTRIBUTE_FULL_NAME = ATTRIBUTE_SHORT_NAME + "Attribute";
    
    public const string ATTRIBUTE_TEXT = 
        $$"""
          /// <auto-generated />
         
          [global::System.AttributeUsage(global::System.AttributeTargets.Enum, Inherited = true, AllowMultiple = true)]
          internal sealed class {{ATTRIBUTE_FULL_NAME}} : global::System.Attribute
          {
              private System.Type _type;
              private bool _shortName;
          
              public {{ATTRIBUTE_FULL_NAME}}(System.Type type, bool shortName = true)
              {
                  _type = type;
                  _shortName = shortName;
              }
          }
          """;
}