namespace UnityAttributes.ShaderProperty;

public static class ShaderPropertyMode
{
    public const string EnumName = "ShaderPropertyMode";
    public static readonly string EnumFullName = $"{nameof(UnityAttributes)}.ShaderProperty."+EnumName;
    public const string EnumText = """
                                   /// <auto-generated />

                                   namespace UnityAttributes.ShaderProperty
                                   {
                                       public enum ShaderPropertyMode
                                       {
                                           Default,
                                           Global,
                                           WithPropertyBlock
                                       }
                                   }
                                   """;
}

