using System.Collections.Generic;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using SourceGeneration.Utils.CodeAnalysisExtensions;
using SourceGeneration.Utils.CodeBuilder;
using SourceGeneration.Utils.Common;

namespace UnityAttributes.ShaderProperty;

[Generator]
public sealed class ShaderPropertyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsSyntaxTargetForGeneration(node),
                transform: static (syntaxContext, token) => GetSemanticTargetForGeneration(syntaxContext, token))
            .Collect()
            .SelectMany(static (array, _) => array.Collect());

        context.RegisterPostInitializationOutput(i =>
        {
            i.AddSource($"{ShaderPropertyType.EnumName}.g", ShaderPropertyType.EnumText);
            i.AddSource($"{ShaderPropertyAttribute.AttributeFullName}.g", ShaderPropertyAttribute.AttributeText);
        });
        
        context.RegisterSourceOutput(classes, GenerateCode!);
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax;
    }
        
    private static Optional<ClassToProcess> GetSemanticTargetForGeneration(GeneratorSyntaxContext ctx, CancellationToken token)
    {
        var classDeclarationSyntax = (ClassDeclarationSyntax) ctx.Node;
        var classDeclarationSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax, token);
        if (classDeclarationSymbol is not ITypeSymbol classTypeSymbol)
        {
            return OptionalExt.None<ClassToProcess>();
        }
        
        var attributes = classDeclarationSyntax.AllAttributesWithName(ShaderPropertyAttribute.AttributeName);
        if (attributes.Count == 0)
        {
            return OptionalExt.None<ClassToProcess>();
        }

        var properties = new List<PropertyToProcess>();
        foreach (var attributeSyntax in attributes)
        {
            if (attributeSyntax.ArgumentList is not { Arguments.Count: >= 2 })
            {
                continue;
            }

            var arguments = attributeSyntax.ArgumentList.Arguments;
            
            // Extract name (first argument)
            string? propertyName = null;
            if (arguments[0].Expression is LiteralExpressionSyntax nameLiteral)
            {
                propertyName = nameLiteral.Token.Text.Trim('"');
            }
            if (string.IsNullOrEmpty(propertyName))
            {
                continue;
            }
            
            // Extract type (second argument) - enum member access
            string? propertyType = null;
            if (arguments[1].Expression is MemberAccessExpressionSyntax typeExpr)
            {
                var memberName = typeExpr.Name.Identifier.Text;
                propertyType = memberName;
            }
            if (string.IsNullOrEmpty(propertyType))
            {
                continue;
            }
            
            // Extract isGlobal (third argument, optional, defaults to false)
            bool isGlobal = false;
            if (arguments.Count > 2 && arguments[2].Expression is LiteralExpressionSyntax isGlobalLiteral)
            {
                isGlobal = isGlobalLiteral.Token.Text == "true";
            }
            
            properties.Add(new PropertyToProcess(propertyName, propertyType, isGlobal));
        }

        if (properties.Count == 0)
        {
            return OptionalExt.None<ClassToProcess>();
        }
            
        return new ClassToProcess(classTypeSymbol, properties);
    }

    private static void GenerateCode(SourceProductionContext context, ClassToProcess classToProcess)
    {
        var code = GenerateCode(classToProcess);
        context.AddSource($"{classToProcess.FullCsharpName}.g", SourceText.From(code, Encoding.UTF8));
    }

    private static string GenerateCode(ClassToProcess classToProcess)
    {
        var builder = new CodeBuilder();
        
        builder.AppendLineWithIdent(Const.AutoGeneratedText);
        builder.AppendLine();
        
        using (new NamespaceBlock(builder, classToProcess.ClassSymbol))
        {
            using (new ParentsBlock(builder, classToProcess.ClassSymbol))
            {
                builder.AppendLineWithIdent("using UnityEngine;");
                builder.AppendLineWithIdent("using System.Collections.Generic;");
                builder.AppendLine();
                builder.AppendIdent().Append("public partial class ").Append(classToProcess.ClassSymbol.Name).AppendLine();
                using (new BracketsBlock(builder))
                {
                    foreach (var property in classToProcess.Properties)
                    {
                        GeneratePropertyCode(builder, property);
                    }
                }
            }
        }
        
        return builder.ToString();
    }

    private static void GeneratePropertyCode(CodeBuilder builder, PropertyToProcess property)
    {
        var propertyName = property.Name;
        if (property.Name.StartsWith("_"))
        {
            propertyName = property.Name.Substring(1);
        }
        propertyName = propertyName.FirstCharToUpper();
        
        builder.AppendLine();
        builder.AppendIdent().Append("public static readonly int ").Append(propertyName).Append(" = Shader.PropertyToID(\"").Append(property.Name).Append("\");");
        builder.AppendLine();
        
        GenerateMethods(builder, property, propertyName);
    }

    private static void GenerateMethods(CodeBuilder builder, PropertyToProcess property, string propertyName)
    {
        var type = property.Type;
        var isGlobal = property.IsGlobal;
        
        switch (type)
        {
            case "Float":
                GenerateFloatMethods(builder, propertyName, isGlobal);
                break;
            case "Integer":
                GenerateIntegerMethods(builder, propertyName, isGlobal);
                break;
            case "Color":
                GenerateColorMethods(builder, propertyName, isGlobal);
                break;
            case "Vector":
                GenerateVectorMethods(builder, propertyName, isGlobal);
                break;
            case "Matrix":
                GenerateMatrixMethods(builder, propertyName, isGlobal);
                break;
            case "Texture":
                GenerateTextureMethods(builder, propertyName, isGlobal);
                break;
            case "Buffer":
                GenerateBufferMethods(builder, propertyName, isGlobal);
                break;
            case "ConstantBuffer":
                GenerateConstantBufferMethods(builder, propertyName, isGlobal);
                break;
            case "FloatArray":
                GenerateFloatArrayMethods(builder, propertyName, isGlobal);
                break;
            case "ColorArray":
                GenerateColorArrayMethods(builder, propertyName, isGlobal);
                break;
            case "VectorArray":
                GenerateVectorArrayMethods(builder, propertyName, isGlobal);
                break;
            case "MatrixArray":
                GenerateMatrixArrayMethods(builder, propertyName, isGlobal);
                break;
        }
    }

    private static void GenerateFloatMethods(CodeBuilder builder, string propertyName, bool isGlobal)
    {
        if (isGlobal)
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(float value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalFloat(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static float Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalFloat(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, float value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetFloat(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static float Get").Append(propertyName).Append("(this Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetFloat(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateIntegerMethods(CodeBuilder builder, string propertyName, bool isGlobal)
    {
        if (isGlobal)
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(int value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalInt(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static int Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalInt(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, int value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetInteger(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static int Get").Append(propertyName).Append("(this Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetInteger(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateColorMethods(CodeBuilder builder, string propertyName, bool isGlobal)
    {
        if (isGlobal)
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Color value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalColor(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Color Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalColor(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, Color value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetColor(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Color Get").Append(propertyName).Append("(this Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetColor(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateVectorMethods(CodeBuilder builder, string propertyName, bool isGlobal)
    {
        if (isGlobal)
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Vector4 value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalVector(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Vector4 Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalVector(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, Vector4 value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetVector(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Vector4 Get").Append(propertyName).Append("(this Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetVector(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateMatrixMethods(CodeBuilder builder, string propertyName, bool isGlobal)
    {
        if (isGlobal)
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Matrix4x4 value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalMatrix(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Matrix4x4 Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalMatrix(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, Matrix4x4 value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetMatrix(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Matrix4x4 Get").Append(propertyName).Append("(this Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetMatrix(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateTextureMethods(CodeBuilder builder, string propertyName, bool isGlobal)
    {
        if (isGlobal)
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Texture value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalTexture(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Texture Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalTexture(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, Texture value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetTexture(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, RenderTexture value, RenderTextureSubElement element)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetTexture(").Append(propertyName).Append(", value, element);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Texture Get").Append(propertyName).Append("(this Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetTexture(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("Offset(this Material material, Vector2 value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetTextureOffset(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Vector2 Get").Append(propertyName).Append("Offset(this Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetTextureOffset(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("Scale(this Material material, Vector2 value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetTextureScale(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Vector2 Get").Append(propertyName).Append("Scale(this Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetTextureScale(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateBufferMethods(CodeBuilder builder, string propertyName, bool isGlobal)
    {
        if (isGlobal)
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeBuffer value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalBuffer(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(GraphicsBuffer value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalBuffer(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
        }
        else
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, ComputeBuffer value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetBuffer(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, GraphicsBuffer value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetBuffer(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateConstantBufferMethods(CodeBuilder builder, string propertyName, bool isGlobal)
    {
        if (isGlobal)
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeBuffer value, int offset, int size)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalConstantBuffer(").Append(propertyName).Append(", value, offset, size);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(GraphicsBuffer value, int offset, int size)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalConstantBuffer(").Append(propertyName).Append(", value, offset, size);");
                builder.AppendLine();
            }
        }
        else
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, ComputeBuffer value, int offset, int size)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetConstantBuffer(").Append(propertyName).Append(", value, offset, size);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, GraphicsBuffer value, int offset, int size)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetConstantBuffer(").Append(propertyName).Append(", value, offset, size);");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateFloatArrayMethods(CodeBuilder builder, string propertyName, bool isGlobal)
    {
        if (isGlobal)
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(List<float> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalFloatArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(float[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalFloatArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static float[] Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalFloatArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, List<float> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetFloatArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, float[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetFloatArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static float[] Get").Append(propertyName).Append("(this Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetFloatArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateColorArrayMethods(CodeBuilder builder, string propertyName, bool isGlobal)
    {
        if (isGlobal)
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(List<Color> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalColorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Color[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalColorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Color[] Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalColorArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, List<Color> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetColorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, Color[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetColorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Color[] Get").Append(propertyName).Append("(this Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetColorArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateVectorArrayMethods(CodeBuilder builder, string propertyName, bool isGlobal)
    {
        if (isGlobal)
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(List<Vector4> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalVectorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Vector4[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalVectorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Vector4[] Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalVectorArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, List<Vector4> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetVectorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, Vector4[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetVectorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Vector4[] Get").Append(propertyName).Append("(this Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetVectorArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateMatrixArrayMethods(CodeBuilder builder, string propertyName, bool isGlobal)
    {
        if (isGlobal)
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(List<Matrix4x4> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalMatrixArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Matrix4x4[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalMatrixArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Matrix4x4[] Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalMatrixArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, List<Matrix4x4> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetMatrixArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this Material material, Matrix4x4[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetMatrixArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Matrix4x4[] Get").Append(propertyName).Append("(this Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetMatrixArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }
}
