namespace UnityAttributes.ShaderProperty;

public static class ShaderPropertyType
{
    public const string EnumName = "ShaderPropertyType";
    public const string EnumFullName = $"UnityAttributes.ShaderProperty.{EnumName}";
    public const string EnumText = """
                                   /// <auto-generated />

                                   namespace UnityAttributes.ShaderProperty
                                   {
                                       public enum ShaderPropertyType
                                       {
                                           Float,
                                           Integer,
                                           Color,
                                           Vector,
                                           Matrix,
                                           Texture,
                                           Buffer,
                                           ConstantBuffer,
                                           FloatArray,
                                           ColorArray,
                                           VectorArray,
                                           MatrixArray
                                       }
                                   }
                                   """;
}

