using System.Collections.Generic;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using SourceGeneration.Utils.CodeAnalysisExtensions;
using SourceGeneration.Utils.CodeBuilder;
using SourceGeneration.Utils.Common;

namespace UnityAttributes.ShaderProperty;

[Generator]
public sealed class ShaderPropertyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsSyntaxTargetForGeneration(node),
                transform: static (syntaxContext, token) => GetSemanticTargetForGeneration(syntaxContext, token))
            .Collect()
            .SelectMany(static (array, _) => array.Collect());

        context.RegisterPostInitializationOutput(i =>
        {
            i.AddSource($"{ShaderPropertyType.EnumName}.g", ShaderPropertyType.EnumText);
            i.AddSource($"{ShaderPropertyMode.EnumName}.g", ShaderPropertyMode.EnumText);
            i.AddSource($"{ShaderPropertyAttribute.AttributeFullName}.g", ShaderPropertyAttribute.AttributeText);
        });
        
        context.RegisterSourceOutput(classes, GenerateCode!);
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax;
    }
        
    private static Optional<ClassToProcess> GetSemanticTargetForGeneration(GeneratorSyntaxContext ctx, CancellationToken token)
    {
        var classDeclarationSyntax = (ClassDeclarationSyntax) ctx.Node;
        var classDeclarationSymbol = ctx.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax, token);
        if (classDeclarationSymbol is not ITypeSymbol classTypeSymbol)
        {
            return OptionalExt.None<ClassToProcess>();
        }
        
        var attributes = classDeclarationSyntax.AllAttributesWithName(ShaderPropertyAttribute.AttributeName);
        if (attributes.Count == 0)
        {
            return OptionalExt.None<ClassToProcess>();
        }

        var properties = new List<PropertyToProcess>();
        foreach (var attributeSyntax in attributes)
        {
            if (attributeSyntax.ArgumentList is not { Arguments.Count: >= 2 })
            {
                continue;
            }

            var arguments = attributeSyntax.ArgumentList.Arguments;
            
            // Extract name (first argument)
            string? propertyName = null;
            if (arguments[0].Expression is LiteralExpressionSyntax nameLiteral)
            {
                propertyName = nameLiteral.Token.Text.Trim('"');
            }
            if (string.IsNullOrEmpty(propertyName))
            {
                continue;
            }
            
            // Extract type (second argument) - enum member access
            string? propertyType = null;
            if (arguments[1].Expression is MemberAccessExpressionSyntax typeExpr)
            {
                var memberName = typeExpr.Name.Identifier.Text;
                propertyType = memberName;
            }
            if (string.IsNullOrEmpty(propertyType))
            {
                continue;
            }
            
            // Extract mode (third argument, optional, defaults to Default)
            string mode = "Default";
            if (arguments.Count > 2 && arguments[2].Expression is MemberAccessExpressionSyntax modeExpr)
            {
                var modeName = modeExpr.Name.Identifier.Text;
                mode = modeName;
            }
            
            properties.Add(new PropertyToProcess(propertyName, propertyType, mode));
        }

        if (properties.Count == 0)
        {
            return OptionalExt.None<ClassToProcess>();
        }
            
        return new ClassToProcess(classTypeSymbol, properties);
    }

    private static void GenerateCode(SourceProductionContext context, ClassToProcess classToProcess)
    {
        var code = GenerateCode(classToProcess);
        context.AddSource($"{classToProcess.FullCsharpName}.g", SourceText.From(code, Encoding.UTF8));
    }

    private static string GenerateCode(ClassToProcess classToProcess)
    {
        var builder = new CodeBuilder();
        
        builder.AppendLineWithIdent(Const.AutoGeneratedText);
        builder.AppendLine();
        
        using (new NamespaceBlock(builder, classToProcess.ClassSymbol))
        {
            using (new ParentsBlock(builder, classToProcess.ClassSymbol))
            {
                builder.AppendLineWithIdent("using UnityEngine;");
                builder.AppendLineWithIdent("using System.Collections.Generic;");
                builder.AppendLine();
                builder.AppendIdent().Append("public partial class ").Append(classToProcess.ClassSymbol.Name).AppendLine();
                using (new BracketsBlock(builder))
                {
                    foreach (var property in classToProcess.Properties)
                    {
                        GeneratePropertyCode(builder, property);
                    }
                }
            }
        }
        
        return builder.ToString();
    }

    private static void GeneratePropertyCode(CodeBuilder builder, PropertyToProcess property)
    {
        var propertyName = property.Name.ToPascalCase();
        
        builder.AppendLine();
        builder.AppendIdent().Append("public static readonly int ").Append(propertyName).Append(" = Shader.PropertyToID(\"").Append(property.Name).Append("\");");
        builder.AppendLine();
        
        GenerateMethods(builder, property, propertyName);
    }

    private static void GenerateMethods(CodeBuilder builder, PropertyToProcess property, string propertyName)
    {
        var type = property.Type;
        var mode = property.Mode;
        
        // Handle Compute mode separately
        if (mode == "Compute")
        {
            GenerateComputeMethods(builder, property, propertyName);
            return;
        }
        
        switch (type)
        {
            case "Float":
                GenerateFloatMethods(builder, propertyName, mode);
                break;
            case "Integer":
                GenerateIntegerMethods(builder, propertyName, mode);
                break;
            case "Bool":
                GenerateBoolMethods(builder, propertyName, mode);
                break;
            case "Color":
                GenerateColorMethods(builder, propertyName, mode);
                break;
            case "Vector":
                GenerateVectorMethods(builder, propertyName, mode);
                break;
            case "Matrix":
                GenerateMatrixMethods(builder, propertyName, mode);
                break;
            case "Texture":
                GenerateTextureMethods(builder, propertyName, mode);
                break;
            case "Buffer":
                GenerateBufferMethods(builder, propertyName, mode);
                break;
            case "ConstantBuffer":
                GenerateConstantBufferMethods(builder, propertyName, mode);
                break;
            case "FloatArray":
                GenerateFloatArrayMethods(builder, propertyName, mode);
                break;
            case "ColorArray":
                GenerateColorArrayMethods(builder, propertyName, mode);
                break;
            case "VectorArray":
                GenerateVectorArrayMethods(builder, propertyName, mode);
                break;
            case "MatrixArray":
                GenerateMatrixArrayMethods(builder, propertyName, mode);
                break;
        }
    }

    private static void GenerateFloatMethods(CodeBuilder builder, string propertyName, string mode)
    {
        if (mode == "Global")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(float value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalFloat(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static float Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalFloat(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else if (mode == "WithPropertyBlock")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, float value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetFloat(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static float Get").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return propertyBlock.GetFloat(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else // Default
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, float value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetFloat(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static float Get").Append(propertyName).Append("(Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetFloat(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateBoolMethods(CodeBuilder builder, string propertyName, string mode)
    {
        if (mode == "Global")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(bool value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalInt(").Append(propertyName).Append(", value ? 1 : 0);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static bool Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalInt(").Append(propertyName).Append(") != 0;");
                builder.AppendLine();
            }
        }
        else if (mode == "WithPropertyBlock")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, bool value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetInt(").Append(propertyName).Append(", value ? 1 : 0);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static bool Get").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return propertyBlock.GetInt(").Append(propertyName).Append(") != 0;");
                builder.AppendLine();
            }
        }
        else // Default
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, bool value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetInt(").Append(propertyName).Append(", value ? 1 : 0);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static bool Get").Append(propertyName).Append("(Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetInt(").Append(propertyName).Append(") != 0;");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateIntegerMethods(CodeBuilder builder, string propertyName, string mode)
    {
        if (mode == "Global")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(int value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalInt(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static int Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalInt(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else if (mode == "WithPropertyBlock")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, int value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetInt(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static int Get").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return propertyBlock.GetInt(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else // Default
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, int value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetInteger(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static int Get").Append(propertyName).Append("(Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetInteger(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateColorMethods(CodeBuilder builder, string propertyName, string mode)
    {
        if (mode == "Global")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Color value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalColor(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Color Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalColor(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else if (mode == "WithPropertyBlock")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, Color value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetColor(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Color Get").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return propertyBlock.GetColor(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else // Default
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, Color value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetColor(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Color Get").Append(propertyName).Append("(Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetColor(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateVectorMethods(CodeBuilder builder, string propertyName, string mode)
    {
        if (mode == "Global")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Vector4 value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalVector(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Vector4 Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalVector(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else if (mode == "WithPropertyBlock")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, Vector4 value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetVector(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Vector4 Get").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return propertyBlock.GetVector(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else // Default
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, Vector4 value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetVector(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Vector4 Get").Append(propertyName).Append("(Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetVector(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateMatrixMethods(CodeBuilder builder, string propertyName, string mode)
    {
        if (mode == "Global")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Matrix4x4 value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalMatrix(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Matrix4x4 Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalMatrix(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else if (mode == "WithPropertyBlock")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, Matrix4x4 value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetMatrix(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Matrix4x4 Get").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return propertyBlock.GetMatrix(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else // Default
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, Matrix4x4 value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetMatrix(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Matrix4x4 Get").Append(propertyName).Append("(Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetMatrix(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateTextureMethods(CodeBuilder builder, string propertyName, string mode)
    {
        if (mode == "Global")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Texture value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalTexture(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Texture Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalTexture(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else if (mode == "WithPropertyBlock")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, Texture value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetTexture(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Texture Get").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return propertyBlock.GetTexture(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("Offset(this MaterialPropertyBlock propertyBlock, Vector2 value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetTextureOffset(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Vector2 Get").Append(propertyName).Append("Offset(this MaterialPropertyBlock propertyBlock)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return propertyBlock.GetTextureOffset(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("Scale(this MaterialPropertyBlock propertyBlock, Vector2 value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetTextureScale(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Vector2 Get").Append(propertyName).Append("Scale(this MaterialPropertyBlock propertyBlock)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return propertyBlock.GetTextureScale(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else // Default
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, Texture value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetTexture(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, RenderTexture value, UnityEngine.Rendering.RenderTextureSubElement element)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetTexture(").Append(propertyName).Append(", value, element);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Texture Get").Append(propertyName).Append("(Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetTexture(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("Offset(Material material, Vector2 value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetTextureOffset(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Vector2 Get").Append(propertyName).Append("Offset(Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetTextureOffset(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("Scale(Material material, Vector2 value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetTextureScale(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Vector2 Get").Append(propertyName).Append("Scale(Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetTextureScale(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateBufferMethods(CodeBuilder builder, string propertyName, string mode)
    {
        if (mode == "Global")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeBuffer value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalBuffer(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(GraphicsBuffer value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalBuffer(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
        }
        else if (mode == "WithPropertyBlock")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, ComputeBuffer value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetBuffer(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, GraphicsBuffer value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetBuffer(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
        }
        else // Default
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, ComputeBuffer value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetBuffer(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, GraphicsBuffer value)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetBuffer(").Append(propertyName).Append(", value);");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateConstantBufferMethods(CodeBuilder builder, string propertyName, string mode)
    {
        if (mode == "Global")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeBuffer value, int offset, int size)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalConstantBuffer(").Append(propertyName).Append(", value, offset, size);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(GraphicsBuffer value, int offset, int size)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalConstantBuffer(").Append(propertyName).Append(", value, offset, size);");
                builder.AppendLine();
            }
        }
        else if (mode == "WithPropertyBlock")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, ComputeBuffer value, int offset, int size)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetConstantBuffer(").Append(propertyName).Append(", value, offset, size);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, GraphicsBuffer value, int offset, int size)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetConstantBuffer(").Append(propertyName).Append(", value, offset, size);");
                builder.AppendLine();
            }
        }
        else // Default
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, ComputeBuffer value, int offset, int size)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetConstantBuffer(").Append(propertyName).Append(", value, offset, size);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, GraphicsBuffer value, int offset, int size)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetConstantBuffer(").Append(propertyName).Append(", value, offset, size);");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateFloatArrayMethods(CodeBuilder builder, string propertyName, string mode)
    {
        if (mode == "Global")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(List<float> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalFloatArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(float[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalFloatArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static float[] Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalFloatArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else if (mode == "WithPropertyBlock")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, List<float> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetFloatArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, float[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetFloatArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static float[] Get").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return propertyBlock.GetFloatArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else // Default
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, List<float> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetFloatArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, float[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetFloatArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static float[] Get").Append(propertyName).Append("(Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetFloatArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateColorArrayMethods(CodeBuilder builder, string propertyName, string mode)
    {
        if (mode == "Global")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(List<Color> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalColorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Color[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalColorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Color[] Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalColorArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else if (mode == "WithPropertyBlock")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, List<Color> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetColorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, Color[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetColorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Color[] Get").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return propertyBlock.GetColorArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else // Default
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, List<Color> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetColorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, Color[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetColorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Color[] Get").Append(propertyName).Append("(Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetColorArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateVectorArrayMethods(CodeBuilder builder, string propertyName, string mode)
    {
        if (mode == "Global")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(List<Vector4> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalVectorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Vector4[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalVectorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Vector4[] Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalVectorArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else if (mode == "WithPropertyBlock")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, List<Vector4> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetVectorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, Vector4[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetVectorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Vector4[] Get").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return propertyBlock.GetVectorArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else // Default
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, List<Vector4> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetVectorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, Vector4[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetVectorArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Vector4[] Get").Append(propertyName).Append("(Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetVectorArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateMatrixArrayMethods(CodeBuilder builder, string propertyName, string mode)
    {
        if (mode == "Global")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(List<Matrix4x4> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalMatrixArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Matrix4x4[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("Shader.SetGlobalMatrixArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Matrix4x4[] Get").Append(propertyName).Append("()");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return Shader.GetGlobalMatrixArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else if (mode == "WithPropertyBlock")
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, List<Matrix4x4> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetMatrixArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock, Matrix4x4[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("propertyBlock.SetMatrixArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Matrix4x4[] Get").Append(propertyName).Append("(this MaterialPropertyBlock propertyBlock)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return propertyBlock.GetMatrixArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
        else // Default
        {
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, List<Matrix4x4> values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetMatrixArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(Material material, Matrix4x4[] values)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("material.SetMatrixArray(").Append(propertyName).Append(", values);");
                builder.AppendLine();
            }
            
            builder.AppendLine();
            builder.AppendIdent().Append("public static Matrix4x4[] Get").Append(propertyName).Append("(Material material)");
            builder.AppendLine();
            using (new BracketsBlock(builder))
            {
                builder.AppendIdent().Append("return material.GetMatrixArray(").Append(propertyName).Append(");");
                builder.AppendLine();
            }
        }
    }

    private static void GenerateComputeMethods(CodeBuilder builder, PropertyToProcess property, string propertyName)
    {
        var type = property.Type;
        
        switch (type)
        {
            case "Float":
                GenerateComputeFloatMethods(builder, propertyName);
                break;
            case "Integer":
                GenerateComputeIntegerMethods(builder, propertyName);
                break;
            case "Bool":
                GenerateComputeBoolMethods(builder, propertyName);
                break;
            case "Color":
                GenerateComputeColorMethods(builder, propertyName);
                break;
            case "Vector":
                GenerateComputeVectorMethods(builder, propertyName);
                break;
            case "Matrix":
                GenerateComputeMatrixMethods(builder, propertyName);
                break;
            case "Texture":
                GenerateComputeTextureMethods(builder, propertyName);
                break;
            case "Buffer":
                GenerateComputeBufferMethods(builder, propertyName);
                break;
            case "ConstantBuffer":
                GenerateComputeConstantBufferMethods(builder, propertyName);
                break;
            // Array types are skipped for Compute mode
        }
    }

    private static void GenerateComputeFloatMethods(CodeBuilder builder, string propertyName)
    {
        builder.AppendLine();
        builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeShader computeShader, float value)");
        builder.AppendLine();
        using (new BracketsBlock(builder))
        {
            builder.AppendIdent().Append("computeShader.SetFloat(").Append(propertyName).Append(", value);");
            builder.AppendLine();
        }
        
        builder.AppendLine();
        builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeShader computeShader, params float[] values)");
        builder.AppendLine();
        using (new BracketsBlock(builder))
        {
            builder.AppendIdent().Append("computeShader.SetFloats(").Append(propertyName).Append(", values);");
            builder.AppendLine();
        }
    }

    private static void GenerateComputeIntegerMethods(CodeBuilder builder, string propertyName)
    {
        builder.AppendLine();
        builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeShader computeShader, int value)");
        builder.AppendLine();
        using (new BracketsBlock(builder))
        {
            builder.AppendIdent().Append("computeShader.SetInt(").Append(propertyName).Append(", value);");
            builder.AppendLine();
        }
        
        builder.AppendLine();
        builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeShader computeShader, params int[] values)");
        builder.AppendLine();
        using (new BracketsBlock(builder))
        {
            builder.AppendIdent().Append("computeShader.SetInts(").Append(propertyName).Append(", values);");
            builder.AppendLine();
        }
    }

    private static void GenerateComputeBoolMethods(CodeBuilder builder, string propertyName)
    {
        builder.AppendLine();
        builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeShader computeShader, bool value)");
        builder.AppendLine();
        using (new BracketsBlock(builder))
        {
            builder.AppendIdent().Append("computeShader.SetBool(").Append(propertyName).Append(", value);");
            builder.AppendLine();
        }
    }

    private static void GenerateComputeColorMethods(CodeBuilder builder, string propertyName)
    {
        builder.AppendLine();
        builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeShader computeShader, Vector4 value)");
        builder.AppendLine();
        using (new BracketsBlock(builder))
        {
            builder.AppendIdent().Append("computeShader.SetVector(").Append(propertyName).Append(", value);");
            builder.AppendLine();
        }
    }

    private static void GenerateComputeVectorMethods(CodeBuilder builder, string propertyName)
    {
        builder.AppendLine();
        builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeShader computeShader, Vector4 value)");
        builder.AppendLine();
        using (new BracketsBlock(builder))
        {
            builder.AppendIdent().Append("computeShader.SetVector(").Append(propertyName).Append(", value);");
            builder.AppendLine();
        }
    }

    private static void GenerateComputeMatrixMethods(CodeBuilder builder, string propertyName)
    {
        builder.AppendLine();
        builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeShader computeShader, Matrix4x4 value)");
        builder.AppendLine();
        using (new BracketsBlock(builder))
        {
            builder.AppendIdent().Append("computeShader.SetMatrix(").Append(propertyName).Append(", value);");
            builder.AppendLine();
        }
    }

    private static void GenerateComputeTextureMethods(CodeBuilder builder, string propertyName)
    {
        builder.AppendLine();
        builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeShader computeShader, int kernelIndex, Texture texture)");
        builder.AppendLine();
        using (new BracketsBlock(builder))
        {
            builder.AppendIdent().Append("computeShader.SetTexture(kernelIndex, ").Append(propertyName).Append(", texture);");
            builder.AppendLine();
        }
        
        builder.AppendLine();
        builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeShader computeShader, int kernelIndex, Texture texture, int mipLevel)");
        builder.AppendLine();
        using (new BracketsBlock(builder))
        {
            builder.AppendIdent().Append("computeShader.SetTexture(kernelIndex, ").Append(propertyName).Append(", texture, mipLevel);");
            builder.AppendLine();
        }
        
        builder.AppendLine();
        builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeShader computeShader, int kernelIndex, RenderTexture texture, int mipLevel, UnityEngine.Rendering.RenderTextureSubElement element)");
        builder.AppendLine();
        using (new BracketsBlock(builder))
        {
            builder.AppendIdent().Append("computeShader.SetTexture(kernelIndex, ").Append(propertyName).Append(", texture, mipLevel, element);");
            builder.AppendLine();
        }
        
        builder.AppendLine();
        builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("FromGlobal(ComputeShader computeShader, int kernelIndex, int globalTextureNameID)");
        builder.AppendLine();
        using (new BracketsBlock(builder))
        {
            builder.AppendIdent().Append("computeShader.SetTextureFromGlobal(kernelIndex, ").Append(propertyName).Append(", globalTextureNameID);");
            builder.AppendLine();
        }
    }

    private static void GenerateComputeBufferMethods(CodeBuilder builder, string propertyName)
    {
        builder.AppendLine();
        builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeShader computeShader, int kernelIndex, ComputeBuffer buffer)");
        builder.AppendLine();
        using (new BracketsBlock(builder))
        {
            builder.AppendIdent().Append("computeShader.SetBuffer(kernelIndex, ").Append(propertyName).Append(", buffer);");
            builder.AppendLine();
        }
        
        builder.AppendLine();
        builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeShader computeShader, int kernelIndex, GraphicsBuffer buffer)");
        builder.AppendLine();
        using (new BracketsBlock(builder))
        {
            builder.AppendIdent().Append("computeShader.SetBuffer(kernelIndex, ").Append(propertyName).Append(", buffer);");
            builder.AppendLine();
        }
    }

    private static void GenerateComputeConstantBufferMethods(CodeBuilder builder, string propertyName)
    {
        builder.AppendLine();
        builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeShader computeShader, ComputeBuffer buffer, int offset, int size)");
        builder.AppendLine();
        using (new BracketsBlock(builder))
        {
            builder.AppendIdent().Append("computeShader.SetConstantBuffer(").Append(propertyName).Append(", buffer, offset, size);");
            builder.AppendLine();
        }
        
        builder.AppendLine();
        builder.AppendIdent().Append("public static void Set").Append(propertyName).Append("(ComputeShader computeShader, GraphicsBuffer buffer, int offset, int size)");
        builder.AppendLine();
        using (new BracketsBlock(builder))
        {
            builder.AppendIdent().Append("computeShader.SetConstantBuffer(").Append(propertyName).Append(", buffer, offset, size);");
            builder.AppendLine();
        }
    }
}
