using UnityAttributes.Common;

namespace UnityAttributes.GenConstructor;

public partial class GenConstructorGenerator {
  public const string AttributeName = "GenConstructorAttribute";
  readonly string attributeText = @$"{Const.AutoGeneratedText}

{generatedCodeAttribute}
[global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = true, AllowMultiple = false)]
internal sealed class {AttributeName} : global::System.Attribute
{{
  public {AttributeName}() {{ }}
}}
";
}