namespace UnityAttributes.GenConstructor;

public partial class GenConstructorGenerator
{
  public const string ATTRIBUTE_NAME = "GenConstructorAttribute";
  public const string ATTRIBUTE_TEXT =
      $$"""
        /// <auto-generated />

        namespace UnityAttributes
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = true, AllowMultiple = false)]
            internal sealed class {{ATTRIBUTE_NAME}} : global::System.Attribute
            {
                public {{ATTRIBUTE_NAME}}() { }
            }
        }

        """;
}