//HintName: RecordAttribute.g.cs
/// <auto-generated />

namespace UnityAttributes
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = true, AllowMultiple = false)]
    internal sealed class RecordAttribute : global::System.Attribute
    {
        internal RecordAttribute()
        {
        }
    }
}
